name: Go Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Linters
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.1
        go install github.com/client9/misspell/cmd/misspell@v0.3.4

    - name: Lint with golangci-lint
      run: golangci-lint run ./...

    - name: Lint with misspell
      run: misspell -locale US -error -source="**/*.{go,md}" --exclude=vendor/**

    - name: Run gofmt
      run: gofmt -s -l -w $(find . -type f -name '*.go' -not -path "./vendor/*")

    - name: Run goimports
      run: goimports -w $(find . -type f -name '*.go' -not -path "./vendor/*")
